import { memo } from "react";
import { Textarea } from "./ui/Textarea";
import { FileText, Info } from "lucide-react";
import { TemplateButton } from "./templates/TemplateButton";
import type { TemplateContext } from "../lib/templates/templateProcessor";

type Props = {
  value: string;
  onChange: (t: string) => void;
  autoGenerated?: boolean;
  readOnly?: boolean;
  templateContext?: TemplateContext;
};

const DiagnosisArea = memo(function DiagnosisArea({
  value,
  onChange,
  autoGenerated,
  readOnly = false,
  templateContext,
}: Props) {
  const charCount = value.length;
  const lineCount = value.split("\n").length;

  return (
    <div className="space-y-2">
      {/* Header con información */}
      <div className="flex items-center justify-between text-sm">
        <div className="flex items-center gap-2 text-[hsl(var(--muted-foreground))]">
          <FileText size={14} />
          <span className="text-sm">Diagnóstico clínico</span>
        </div>
        <div className="flex items-center gap-3 text-xs text-[hsl(var(--muted-foreground))]">
          {autoGenerated && (
            <div className="flex items-center gap-1 px-2 py-1 rounded-md bg-[hsl(var(--muted))]">
              <Info size={12} />
              <span>Auto-generado</span>
            </div>
          )}
          <span>
            {lineCount} línea{lineCount !== 1 ? "s" : ""}
          </span>
          <span>{charCount} caracteres</span>
        </div>
      </div>

      {/* Textarea */}
      <div className="relative">
        <Textarea
          value={value}
          onChange={(e) => {
            if (readOnly) return;
            onChange(e.target.value);
          }}
          placeholder="Diagnóstico detallado..."
          className="min-h-[150px] font-mono text-sm pr-10"
          rows={6}
          disabled={readOnly}
          aria-readonly={readOnly}
        />
        {!readOnly && templateContext && (
          <TemplateButton
            kind="diagnosis"
            onInsert={(text) => onChange(text)}
            context={templateContext}
            className="absolute top-2 right-2"
          />
        )}
      </div>

      {/* Ayuda */}
      <div className="flex items-start gap-2 p-3 rounded-lg bg-[hsl(var(--muted))] text-xs text-[hsl(var(--muted-foreground))]">
        <Info size={14} className="mt-0.5 flex-shrink-0" />
        <div>
          <strong className="text-[hsl(var(--foreground))]">Tip:</strong> El
          diagnóstico se genera automáticamente cuando seleccionas condiciones
          en el odontograma, pero puedes editarlo manualmente en cualquier
          momento.
        </div>
      </div>

      {readOnly && (
        <div className="text-xs text-[hsl(var(--muted-foreground))]">
          Modo lectura: esta sesión está bloqueada para edición.
        </div>
      )}
    </div>
  );
});

DiagnosisArea.displayName = "DiagnosisArea";

export default DiagnosisArea;
