// src/components/DiagnosisArea.tsx
import { memo } from "react";
import { Textarea } from "./ui/Textarea";
import { FileText, Info } from "lucide-react";

type Props = {
  value: string;
  onChange: (t: string) => void;
  autoGenerated?: boolean;
};

const DiagnosisArea = memo(function DiagnosisArea({
  value,
  onChange,
  autoGenerated,
}: Props) {
  const charCount = value.length;
  const lineCount = value.split("\n").length;

  return (
    <div className="space-y-2">
      {/* Header con información */}
      <div className="flex items-center justify-between text-sm">
        <div className="flex items-center gap-2 text-[hsl(var(--muted-foreground))]">
          <FileText size={14} />
          <span className="text-sm">Diagnóstico clínico</span>
        </div>
        <div className="flex items-center gap-3 text-xs text-[hsl(var(--muted-foreground))]">
          {autoGenerated && (
            <div className="flex items-center gap-1 px-2 py-1 rounded-md bg-[hsl(var(--muted))]">
              <Info size={12} />
              <span>Auto-generado</span>
            </div>
          )}
          <span>
            {lineCount} línea{lineCount !== 1 ? "s" : ""}
          </span>
          <span>{charCount} caracteres</span>
        </div>
      </div>

      {/* Textarea */}
      <Textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Diagnóstico detallado..."
        className="min-h-[120px] font-mono text-sm"
        rows={6}
      />

      {/* Ayuda */}
      <div className="flex items-start gap-2 p-3 rounded-lg bg-[hsl(var(--muted))] text-xs text-[hsl(var(--muted-foreground))]">
        <Info size={14} className="mt-0.5 flex-shrink-0" />
        <div>
          <strong className="text-[hsl(var(--foreground))]">Tip:</strong> El
          diagnóstico se genera automáticamente cuando seleccionas condiciones
          en el odontograma, pero puedes editarlo manualmente en cualquier
          momento.
        </div>
      </div>
    </div>
  );
});

DiagnosisArea.displayName = "DiagnosisArea";

export default DiagnosisArea;
