import { memo } from "react";
import { Activity, FileText } from "lucide-react";

import type { ToothDx } from "../lib/types";
import Section from "./Section"; // ajusta el path si es distinto
import Odontogram from "./Odontogram";
import DiagnosisArea from "./DiagnosisArea";
import { Alert } from "./ui/Alert";

type Props = {
  toothDx: ToothDx;
  onToothDxChange: (next: ToothDx) => void;

  diagnosisFromTeeth?: string | null;
  manualDiagnosis: string;
  onManualDiagnosisChange: (next: string) => void;
};

const OdontogramDiagnosisSection = memo(function OdontogramDiagnosisSection({
  toothDx,
  onToothDxChange,
  diagnosisFromTeeth,
  manualDiagnosis,
  onManualDiagnosisChange,
}: Props) {
  return (
    <Section title="Odontograma por Cuadrantes" icon={<Activity size={20} />}>
      {/* Bloque 1: Odontograma full-width */}
      <div>
        <Odontogram value={toothDx} onChange={onToothDxChange} />
      </div>

      {/* Separador visual */}
      <div className="my-4 h-px bg-[hsl(var(--border))]" />

      {/* Bloque 2: Diagnóstico, debajo y también full-width */}
      <div className="space-y-3">
        <div className="flex items-center gap-2 text-sm font-semibold text-[hsl(var(--foreground))]"></div>

        {diagnosisFromTeeth && (
          <Alert variant="info" className="mb-1">
            <div className="flex items-start gap-2">
              <FileText size={18} />
              <div className="text-sm">
                <strong>Diagnóstico automático del odontograma</strong>
                <p className="mt-1 whitespace-pre-line">{diagnosisFromTeeth}</p>
              </div>
            </div>
          </Alert>
        )}

        <DiagnosisArea
          value={manualDiagnosis}
          onChange={onManualDiagnosisChange}
          autoGenerated={Boolean(diagnosisFromTeeth)}
        />
      </div>
    </Section>
  );
});

export default OdontogramDiagnosisSection;
