import { memo } from "react";
import { Activity, FileText } from "lucide-react";

import type { ToothDx, SessionWithItems } from "../lib/types";
import Section from "./Section"; // ajusta el path si es distinto
import Odontogram from "./Odontogram";
import DiagnosisArea from "./DiagnosisArea";
import { Alert } from "./ui/Alert";
import { Badge } from "./ui/Badge";
import { SessionContextBar } from "./sessions/SessionContextBar";

type Props = {
  toothDx: ToothDx;
  onToothDxChange: (next: ToothDx) => void;

  diagnosisFromTeeth?: string | null;
  manualDiagnosis: string;
  onManualDiagnosisChange: (next: string) => void;
  readOnly?: boolean;
  activeSessionId: number | null;
  sessions: SessionWithItems[];
  onSessionChange: (sessionId: number | null) => void;
  lastSavedSession: SessionWithItems | null;
  lastSavedOrdinal?: number | null;
};

const OdontogramDiagnosisSection = memo(function OdontogramDiagnosisSection({
  toothDx,
  onToothDxChange,
  diagnosisFromTeeth,
  manualDiagnosis,
  onManualDiagnosisChange,
  readOnly = false,
  activeSessionId,
  sessions,
  onSessionChange,
  lastSavedSession,
  lastSavedOrdinal,
}: Props) {
  const lastSavedLabel = lastSavedSession
    ? `Última vez editado: Sesión #${lastSavedOrdinal ?? "?"} - ${lastSavedSession.session.date || "Sin fecha"}`
    : "Sin odontograma previo";

  return (
    <Section title="Odontograma por Cuadrantes" icon={<Activity size={20} />}>
      <SessionContextBar
        activeSessionId={activeSessionId}
        sessions={sessions}
        onSessionChange={onSessionChange}
      />

      {readOnly && (
        <Alert variant="info" className="mb-3">
          <div className="flex items-center gap-2">
            <FileText size={18} />
            <div>
              <div className="font-semibold">Modo lectura</div>
              <p className="text-sm text-[hsl(var(--muted-foreground))]">
                Estás revisando una sesión guardada.
              </p>
            </div>
          </div>
        </Alert>
      )}

      <div className="mb-3 flex justify-end">
        <Badge variant="info" className="text-xs">
          {lastSavedLabel}
        </Badge>
      </div>

      {/* Bloque 1: Odontograma full-width */}
      <div>
        <Odontogram
          value={toothDx}
          onChange={onToothDxChange}
          readOnly={readOnly}
        />
      </div>

      {/* Separador visual */}
      <div className="my-4 h-px bg-[hsl(var(--border))]" />

      {/* Bloque 2: Diagnóstico, debajo y también full-width */}
      <div className="space-y-3">
        <div className="flex items-center gap-2 text-sm font-semibold text-[hsl(var(--foreground))]"></div>

        {diagnosisFromTeeth && (
          <Alert variant="info" className="mb-1">
            <div className="flex items-start gap-2">
              <FileText size={18} />
              <div className="text-sm">
                <strong>Diagnóstico automático del odontograma</strong>
                <p className="mt-1 whitespace-pre-line">{diagnosisFromTeeth}</p>
              </div>
            </div>
          </Alert>
        )}

        <DiagnosisArea
          value={manualDiagnosis}
          onChange={onManualDiagnosisChange}
          autoGenerated={Boolean(diagnosisFromTeeth)}
          readOnly={readOnly}
        />
      </div>
    </Section>
  );
});

export default OdontogramDiagnosisSection;
